### ISSUE TITLE
Pass user token to Algolia searches

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/apollos-api#216]
Aloglia dashboard/reports show all operations as belonging to "2" users.
Ideally, we'd pass the `userToken` along so we know who is searching for what.

**Comment by rkdavidson** [comment]
Not important for now, but while I'm reviewing old issues...

@asleepingpanda, what does the ideal state look like around this?
Do we need to know individual users' search queries, and are there any privacy considerations around that?

My theory for now is that the "two users" doing all the Algolia searches are either web/app or test/prod. So either platform or environmental distinction.

**Comment by asleepingpanda** [comment]
Yeah this is an interesting one. Maybe we could start with this question:

What is an Algolia user?

If the Algolia user refers to a reference of the User Id, then I think there is still value in doing this (not blocking any launch of anything, just as a follow up) because of a longer strategy around "suggested" content.

I think we spend like 15-20 minutes understanding what that data is exactly referring to and then making a decision from there if this is a relevant problem or not.

**Comment by asleepingpanda** [comment]
@rkdavidson any updates on this by any chance?

**Comment by jordanwade** [comment]
Here is the userToken documentation I found. Not sure if it setup for the new Algolia personalization stuff they have in beta, but it might be a good starting point to track users and give personalized results.
https://www.algolia.com/doc/api-reference/api-parameters/userToken/

![image](https://user-images.githubusercontent.com/2528817/119549056-786d4500-bd5c-11eb-88ad-e8b33741cc1b.png)

**Comment by jordanwade** [comment]
Quick video explaining their Personalization setup.
https://youtu.be/ymd7VL233TQ
